// <auto-generated />
using System;
using LyricsCollector.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LyricsCollector.Migrations
{
    [DbContext(typeof(LyricsCollectorDbContext))]
    [Migration("20210120113541_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("LyricsCollector.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CollectionOfUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionOfUserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("LyricsCollector.Entities.CollectionLyrics", b =>
                {
                    b.Property<int>("LyricsId")
                        .HasColumnType("int");

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.HasKey("LyricsId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("CollectionLyrics");
                });

            modelBuilder.Entity("LyricsCollector.Entities.Lyrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SongLyrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lyrics");
                });

            modelBuilder.Entity("LyricsCollector.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LyricsCollector.Entities.Collection", b =>
                {
                    b.HasOne("LyricsCollector.Entities.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("CollectionOfUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LyricsCollector.Entities.CollectionLyrics", b =>
                {
                    b.HasOne("LyricsCollector.Entities.Collection", "Collection")
                        .WithMany("Lyrics")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LyricsCollector.Entities.Lyrics", "Lyrics")
                        .WithMany("CollectionLyrics")
                        .HasForeignKey("LyricsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Lyrics");
                });

            modelBuilder.Entity("LyricsCollector.Entities.Collection", b =>
                {
                    b.Navigation("Lyrics");
                });

            modelBuilder.Entity("LyricsCollector.Entities.Lyrics", b =>
                {
                    b.Navigation("CollectionLyrics");
                });

            modelBuilder.Entity("LyricsCollector.Entities.User", b =>
                {
                    b.Navigation("Collections");
                });
#pragma warning restore 612, 618
        }
    }
}
